[package]
name = "dkdto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
schemars = "0.7"
rocket_okapi = "0.5.1"
